name: foss_warn
description: Eine FOSS Umsetzung von NINA
publish_to: 'none'
version: 0.7.0+30

environment:
  sdk: ">=2.17.0 <3.13.3"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.1.0
  flutter_local_notifications: ^16.2.0
  shared_preferences: ^2.2.2
  shared_preferences_android: ^2.2.1
  provider: ^6.1.1
  rxdart: ^0.27.7
  url_launcher: ^6.2.2
  share_plus: ^7.2.1
  android_alarm_manager_plus: ^3.0.4
  intl: any # for localizations

  # used by the map
  flutter_map: ^6.1.0
  flutter_map_geojson: ^1.0.5
  latlong2: ^0.9.0

  #icons_launcher: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

icons_launcher:
  image_path: "assets/app_icon/app_icon.png"
  platforms:
    android:
      enable: true
      image_path: "assets/app_icon/app_icon.png"
      adaptive_background_color: '#cfe5ff'
      adaptive_foreground_image: "assets/app_icon/adaptive_icon.png"
      adaptive_monochrome_image: "assets/app_icon/adaptive_monochrome_app_icon.png"

flutter:
  generate: true # for localizations
  uses-material-design: true
  assets:
   # welcome screen
   - assets/app_icon/app_icon.png
   - assets/location.png
   - assets/battery.png
   - assets/check.png
   - assets/steps.png
   - assets/paragraph.png
