# This is a basic workflow to help you get started with Actions

name: build apk

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  JAVA_VERSION: "17.x"
  FLUTTER_VERSION: "3.12.0"
  FLUTTER_CHANNEL: 'stable'
  PROPERTIES_PATH: "./android/key.properties"
  STOREFILE_PATH: "key.jks"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        java-version: ${{env.JAVA_VERSION}}
        distribution: adopt
        
    - run: |
        # Creating the key.properties file
        echo storePassword=${{ secrets.STORE_PASSWORD }} > ${{env.PROPERTIES_PATH}}
        echo keyPassword=${{ secrets.KEY_PASSWORD }} >> ${{env.PROPERTIES_PATH}}
        echo keyAlias=${{ secrets.KEY_ALIAS }} >> ${{env.PROPERTIES_PATH}}
        echo storeFile=${{ env.STOREFILE_PATH }} >> ${{env.PROPERTIES_PATH}}
        # '>' = overwrites '>>' = appends
        echo print key.properties with debug values
        cat ${{env.PROPERTIES_PATH}}
    # Decoding base64 key into a file
    - run: |
        # create key.jks
        echo "${{ secrets.KEYSTORE }}" | base64 --decode > android/app/key.jks
    
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{env.FLUTTER_VERSION}}
        channel: ${{env.FLUTTER_CHANNEL}}
    - run: flutter --version
    - run: flutter pub get
    - run: flutter gen-l10n # generate translation strings
    - run: flutter test
    - run: flutter build apk # build fat APK 
    - run: flutter build apk --split-per-abi
    - uses: actions/upload-artifact@v2
      with:
        name: release-apk
        path: |
          build/app/outputs/flutter-apk/app-release.apk
          build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
          build/app/outputs/apk/release/app-arm64-v8a-release.apk
          build/app/outputs/apk/release/app-x86_64-release.apk
